services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sya_client_server
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
