import type { IProduct, IProductStats } from ".";

const types = [
  "food_beverages_tobacco",
  "animals_pets",
  "money_insurance",
  "beauty_wellbeing",
  "construction_manufactoring",
  "education_training",
  "electronics_technology",
  "events_entertainment",
  "hobbies_crafts",
  "home_garden",
  "media_publishing",
  "restaurants_bars",
  "health_medical",
  "utilities",
  "home_services",
  "business_services",
  "legal_services_government",
  "public_local_services",
  "shopping_fashion",
  "sports",
  "travel_vacation",
  "vehicles_transportation",
] as const;

const subtypes = [
  "agriculture_produce",
  "beer_wine",
  "beverages_liquor",
  "candy_chocolate",
  "bakery_pastry",
  "coffee_tea",
  "lunch_catering",
  "grocery_stores_markets",
  "asian_grocery_stores",
  "fruits_vegetables",
  "food_production",
  "smoking_tobacco",
  "meat_seafood_eggs",
  "pet_stores",
  "cats_dogs",
  "horses_riding",
  "animal_parks_zoo",
  "animal_health",
  "pet_services",
  "insurance",
  "banking_money",
  "accounting_tax",
  "real_estate",
  "investments_wealth",
  "credit_debt_services",
  "wellness_spa",
  "personal_care",
  "cosmetics_makeup",
  "salons_clinics",
  "hair_care_styling",
  "tattoos_piercings",
  "yoga_meditation",
  "architects_engineers",
  "contractors_consultants",
  "factory_equipment",
  "manufacturing",
  "industrial_supplies",
  "garden_landscaping",
  "building_materials",
  "tools_equipment",
  "chemicals_plastic",
  "construction_services",
  "production_services",
  "language_learning",
  "colleges_universities",
  "music_theater_classes",
  "school_high_school",
  "specials_schools",
  "vocational_training",
  "courses_classes",
  "education_services",
  "appliances_electronics",
  "audio_visual",
  "internet_software",
  "computers_phones",
  "repair_services",
  "clubbing_nightlife",
  "adult_entertainment",
  "childrens_entertainment",
  "gaming",
  "gambling",
  "events_venues",
  "wedding_party",
  "museums_exibits",
  "music_movies",
  "theater_opera",
  "outdoor_activities",
  "art_handicraft",
  "astrology_numerology",
  "fishing_hunting",
  "needlework_knitting",
  "hobbies",
  "music_instruments",
  "painting_paper",
  "metal_stone_glass_work",
  "home_improvements",
  "decoration_interior",
  "energy_heating",
  "garden_pond",
  "home_goods_stores",
  "furniture_stores",
  "cultural_goods",
  "bathroom_kitchen",
  "home_garden_services",
  "fabric_stationary",
  "books_magazines",
  "media_information",
  "photography",
  "video_sound",
  "takeaway",
  "bars_cafes",
  "african_pacific_cuisine",
  "chinese_korean_cuisine",
  "north_south_american_cuisine",
  "southeast_asian_cuisine",
  "middle_eastern_cuisine",
  "european_cuisine",
  "japanese_cuisine",
  "mediterranean_cuisine",
  "general_restaurants",
  "vegetarian_diet",
  "physical_aids",
  "clinics",
  "diagnostics_testing",
  "doctors_surgeons",
  "health_equipment",
  "hospital_emergency",
  "pregnancy_children",
  "medical_specialists",
  "pharmacy_medicine",
  "mental_health",
  "dental_services",
  "therapy_senior_health",
  "vision_hearing",
  "energy_power",
  "oil_fuel",
  "water_utilities",
  "craftsman",
  "moving_storage",
  "house_sitting_security",
  "plumbing_sanitation",
  "cleaning_service_providers",
  "repair_service_providers",
  "house_services",
  "administration_services",
  "associations_centers",
  "wholesale",
  "import_export",
  "print_graphic_design",
  "research_development",
  "it_communication",
  "office_space_supplies",
  "hr_recruiting",
  "shipping_logistics",
  "sales_marketing",
  "lawyers_attorneys",
  "libraries_archives",
  "government_department",
  "municipal_department",
  "customs_toll",
  "law_enforcement",
  "legal_service_providers",
  "registration_services",
  "employment_career",
  "kids_family",
  "funeral_memorial",
  "waste_management",
  "religious_institutions",
  "military_veteran",
  "nature_environment",
  "professional_organizations",
  "shelters_homes",
  "public_services_welfare",
  "housing_associations",
  "accessories",
  "jewelry_watches",
  "malls_marketplaces",
  "costume_wedding",
  "clothing_rental_repair",
  "clothing_underwear",
  "martial_arts_wrestling",
  "dancing_gymnastics",
  "equipment_associations",
  "fitness_weight_lifting",
  "golf_ultimate",
  "hockey_ice_skating",
  "ball_games",
  "bat-and-ball_games",
  "bowls_lawn_sports",
  "swimming_water_sports",
  "shooting_target_sports",
  "outdoor_winter_sports",
  "extreme_sports",
  "tennis_racquet_sports",
  "activities_tours",
  "travel_agencies",
  "airlines_air_travel",
  "accomodations_lodging",
  "hotels",
  "airports_parking",
  "other_vehicles_trailers",
  "vehical_rental",
  "motorcycle_powersports",
  "auto_parts_wheels",
  "vehicle_repair_fuel",
  "taxis_public_transport",
  "air_water_transport",
  "bicycles",
  "cars_trucks",
] as const;

export type IProductType = (typeof types)[number];
export type IProductSubtype = (typeof subtypes)[number];

export interface IProductSearchParams {
  q?: string;
  type?: IProductType | IProductSubtype;
  page?: number;
  pageSize?: number;
  scoreMoreThan?: number;
  sort?: "latest_review" | "highest_rated" | "best_rated";
  [key: string]: any;
}

export interface IProductSearchResult {
  products: IProductAllData[];
  page: number;
  totalPages: number;
  total: number;
  pageSize: number;
  fromto: [number, number];
}

export interface IProductAllData extends IProduct {
  stats: IProductStats;
}
